dev:
  url: {{envOr "DEV_DATABASE_URL" "postgres://postgres:password@127.0.0.1:5432/dev-mydb?sslmode=disable"}}

test:
  url: {{envOr "TEST_DATABASE_URL" "postgres://postgres:password@127.0.0.1:5432/test-mydb?sslmode=disable"}}

prod:
  url: {{envOr "DATABASE_URL" "postgres://postgres:postgres@127.0.0.1:5432/mydb"}}
